version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fugue-events"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LogRetentionInDays=\"30\""
